#!/usr/bin/perl -w
use lib "/usr/local/netfpga/lib/Perl5";
use strict;

# ==============================
# Register Addresses
# ==============================

my $CPU_CMD   = 0x2000100;
my $CPU_ADDR  = 0x2000104;
my $CPU_WDATA = 0x2000108;
my $CPU_RDATA = 0x200010c;

# ==============================
# Register Access Helpers
# ==============================

sub regwrite {
   my ($addr, $value) = @_;
   my $cmd = sprintf("regwrite $addr 0x%08x", $value);
   `$cmd`;
}

sub regread {
   my ($addr) = @_;
   my $cmd = sprintf("regread $addr");
   my @out = `$cmd`;
   my $result = $out[0];

   if ($result =~ m/Reg (0x[0-9a-f]+) \((\d+)\):\s+(0x[0-9a-f]+) \((\d+)\)/) {
      return $3;
   }
   return "0x00000000";
}

# ==============================
# CPU Interface Functions
# ==============================

sub disable_cpu {
   print "Disabling CPU...\n";
   regwrite($CPU_CMD, 0x0);
}

sub enable_cpu {
   print "Enabling CPU...\n";
   regwrite($CPU_CMD, 0x4);   # bit2 = cpu_enable
}

sub write_mem {
   my ($addr, $data) = @_;
   print "Writing 0x$data to memory address $addr\n";
   regwrite($CPU_ADDR,  $addr);
   regwrite($CPU_WDATA, hex($data));
   regwrite($CPU_CMD,   0x1);   # write bit
}

sub read_mem {
   my ($addr) = @_;
   print "Reading memory address $addr\n";
   regwrite($CPU_ADDR, $addr);
   regwrite($CPU_CMD,  0x2);    # read bit
   my $val = regread($CPU_RDATA);
   print "Read value: $val\n";
}

sub show_all {
   print "CPU_CMD:   ", regread($CPU_CMD),   "\n";
   print "CPU_ADDR:  ", regread($CPU_ADDR),  "\n";
   print "CPU_WDATA: ", regread($CPU_WDATA), "\n";
   print "CPU_RDATA: ", regread($CPU_RDATA), "\n";
}

sub usage {
   print "Usage: cpureg <command> [args]\n";
   print "Commands:\n";
   print "  disable                Disable CPU execution\n";
   print "  enable                 Enable CPU execution\n";
   print "  write <addr> <data>    Write hex data to memory\n";
   print "  read <addr>            Read memory\n";
   print "  allregs                Display all CPU registers\n";
   print "\nExamples:\n";
   print "  cpureg write 10 12345678\n";
   print "  cpureg read 10\n";
   print "  cpureg write 512 aabbccdd\n";
   print "  cpureg read 512\n";
}

# ==============================
# Command Parsing
# ==============================

my $numargs = $#ARGV + 1;
if ($numargs < 1) {
   usage();
   exit(1);
}

my $cmd = $ARGV[0];

if ($cmd eq "disable") {
   disable_cpu();
}
elsif ($cmd eq "enable") {
   enable_cpu();
}
elsif ($cmd eq "write") {
   if ($numargs < 3) {
      usage();
      exit(1);
   }
   write_mem($ARGV[1], $ARGV[2]);
}
elsif ($cmd eq "read") {
   if ($numargs < 2) {
      usage();
      exit(1);
   }
   read_mem($ARGV[1]);
}
elsif ($cmd eq "allregs") {
   show_all();
}
else {
   print "Unrecognized command $cmd\n";
   usage();
   exit(1);
}
